# Generated by Django 4.1.5 on 2023-01-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(max_length=50)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(max_length=50)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
