# Generated by Django 4.1.5 on 2023-01-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_order_details_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='username',
        ),
    ]
