# Generated by Django 4.1.5 on 2023-01-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_delete_order_details_delete_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_url', models.URLField(blank=True)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment_details',
        ),
    ]
