# Generated by Django 4.1.5 on 2023-01-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_order_details_delete_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='status',
            field=models.CharField(default='Unsuccessful', max_length=50),
        ),
    ]
