# Generated by Django 4.1.5 on 2023-01-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_order_details_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='order_amount',
            field=models.DecimalField(blank='True', decimal_places=2, max_digits=10),
        ),
    ]
