# Generated by Django 4.1.5 on 2023-01-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_order_details_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
